---
title: "EC 421"
subtitle: "Midterm Topics"
#author: "Connor Lennon"
date: "Spring 2021"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

**Note:** In general, you do not need to memorize proofs. Just understand the steps and intuitively get a grasp on how they might be used to inform results. I might ask how you get from one step to the next, or at most 2 steps from where we begin. I won't ask you to write down a full proof - that's not helpful for you or I.

## Slides 1: Intro

- The goal of econometrics
- Regression notation
- Basic concept of causality

## Slides 2: Review I

- Population vs. sample
  - Parameters vs. sample estimates
  - Estimators and uncertainty
- Uncertainty
  - Standard errors
  - Hypothesis testing
    - _t_ tests
    - _F_ tests
    - Forming hypotheses
    - critical value
    - *p*-value
  - Confidence intervals
- Linear regression and OLS
  - "Best-fit" line
  - Residuals
  - SSE
  - Estimators: bias and variance
  - Statistical inference
  - Variance (and standard error) of the OLS estimator
  - Regressions with R's `lm` function

---
class: clear

## Slides 3: Review II

- Simple and multiple linear regression
- Model fit
  - R squared
  - Overfitting/R squared mechanically increases
  - Adjusted R squared
- Omitted-variable bias
- Interpreting coefficients
  - Simple linear regression
  - Multiple linear regression (ceterus paribus)
  - Continuous explanatory variables
  - Categorical explanatory variables
  - Interactions
  - Specifications
    - Linear-linear
    - Log-linear
    - Log-log
- Inference vs. prediction

## Slides 4: Heteroskedasticity

- The meaning of each of our assumptions/requirements
- Heteroskedasticity
  - What it is
  - What it looks like
  - Consequences for OLS
- Tests for heteroskedasticity
  - Goldfeld-Quandt test
  - Breusch-Pagan test
  - White test
  - Chi-squared distribution
  - Null and alternative hypotheses of each test
  - Interpretations/conclusions for each
  - Strengths and weaknesses of each test

---
class: clear

## Slides 5: Living with Heteroskedasticity

- Misspecification
- Weighted least squares and FGLS
- Heteroskedasticity-robust standard errors

## Slides 6: Asymptotics and Consistency

- Asymptotics
  - Compared to 'finite-sample' attributes (probability limits vs. expected values)
  - Probability limits
- Consistency (vs. Bias)
- Signing the direction of inconsistency from omitted variables.
- Measurement error and attenuation bias: What are they?
- Examples of measurement error

## Slides 7: Time Series

- Basics of time-series data: How do they differ from cross-sectional data?
- Static models *vs.* dynamic models
- How do we specify time series models?
- How do we estimate 'persistence' effects using time series tools?

```{r, print pdfs, echo = F, eval = F}
pagedown::chrome_print(
  input = "MidtermReview/Midterm_Topics.html",
  timeout = 60
)
```